# Settings for LPJmL specifically for coupling (pycoupler)
#   (not covered by LPJmL's direct config)
lpjml_settings:
    country_code_to_name: true # same for region code
    iso_country_code: true

# Variables to be written to copan_core_data table file 
output:
    individual:
        - "behaviour"
        - "avg_hdate"
        - "soilc"
        - "cropyield"

# Define how copan_core_data table file should be written
output_settings:
    write_lon_lat: true
    format: "csv"  # "csv", "feather" (fast binary table format)

# added by luana for less frequent updates TODO does that make sense here?
min_update_interval: 20  # in years
# Define which individual variables map with coupled LPJmL input variables
coupling_map:
    behaviour: ["with_tillage"]  # "residue_on_field"

# Analogous to LPJmL pftpar, define the AFT parameters for the two different
#   farmer types
aftpar:
    # AFT for progressive farmer who more likely tends to switch to
    #   regenerative agriculture
    progressive_minded:
        pbc: &pbc_value 0.5
        weight_attitude: 0.667
        weight_yield: 2
        weight_soil: 3.5
        weight_norm: 0.333
        weight_social_learning: 0.5
        weight_own_land: 0.5
        # duration of waiting time before switching to another strategy
        strategy_switch_duration: 10 # years

    # AFT for conservative/traditional values following farmer tending to stay
    #   with conventional agriculture
    conservative_minded:
        pbc: *pbc_value
        weight_attitude: 0.5
        weight_yield: 3.5
        weight_soil: 2
        weight_norm: 0.5
        weight_social_learning: 0.5
        weight_own_land: 0.5
        # duration of waiting time before switching to another strategy
        strategy_switch_duration: 10 # years
